<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ApacheKafka-0c0682e8-8179-43d4-864b-0c4a143f0b4b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" Version="2.5.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0"/>
    </ItemGroup>
</Project>
